---
image: atlassian/default-image:3

pipelines:
  tags:
    v*:
      - step:
          name: 'Docker push'
          deployment: production
          script:
            - echo $BITBUCKET_REPO_SLUG
            - echo ${DOCKER_HUB_USERNAME}
            - echo ${DOCKERHUB_PASSWORD} | docker login -u "$DOCKERHUB_USERNAME" --password-stdin docker.io
            - docker build -t ${DOCKERHUB_USERNAME}/$BITBUCKET_REPO_SLUG:$BITBUCKET_TAG .
            - docker push ${DOCKERHUB_USERNAME}/$BITBUCKET_REPO_SLUG:$BITBUCKET_TAG
options:
  docker: true
