image: atlassian/default-image:2

pipelines:
  tags:
    v*:
      - step:
          name: 'Docker push'
          script:
            - echo $BITBUCKET_REPO_SLUG
            - docker login -u $CANISTER_USERNAME -p $CANISTER_PASSWORD cloud.canister.io:5000
            - docker build -t cloud.canister.io:5000/$CANISTER_USERNAME/$BITBUCKET_REPO_SLUG:$BITBUCKET_TAG .
            - docker push cloud.canister.io:5000/$CANISTER_USERNAME/$BITBUCKET_REPO_SLUG
options:
  docker: true
